#!/bin/env python

from pathlib import Path
import subprocess
import sys

levels = [0, 1, 5, 15, 50, 100]

if len(sys.argv) < 2: sys.exit(-1)
direction = sys.argv[1]
if direction not in ("up", "down"): sys.exit(-1)

base = Path("/sys/class/backlight/intel_backlight")

with open(base / "brightness", "r") as f: current_raw = int(f.read().strip())
with open(base / "max_brightness", "r") as f: max_ = int(f.read().strip())

if direction == "down": levels = levels[::-1]

current = int(round(current_raw * 100 / max_))
if current not in levels:
    closest = levels[0]
    smallest_difference = abs(current - levels[0])
    for level in levels[1:]:
        difference = abs(current - level)
        if difference <= smallest_difference:
            closest = level
            smallest_difference = difference
    current = closest

i = levels.index(current) + 1
if i >= len(levels): sys.exit(-2)
subprocess.check_output(["backlight_control", str(levels[i])])
